name: Stables
version: 1.0
description: >
  Adds more features to horses
author: Tritania
website: https://github.com/tritania/Stables

main: org.tritania.stables.Stables

commands:
  htpa:
    description: Teleport a player on a horse to you
    aliases: []
    usage: /<command> [playername]
  htpahere:
    description: Teleport yourself on a horse to someone else
    aliases: []
    usage: /<command> [playername]
  haccept:
    description: accept a teleport
    aliases: []
    usage: /<command>
  hdeny:
    description: deny a teleport
    aliases: []
    usage: /<command>
  setstable:
    description: sets a stable for your horse
    aliases: []
    usage: /<command> [stable name]
  delstable:
    description: deletes a stable
    aliases: []
    usage: /<command> [stable name]
  stable:
    description: teleports your horse back to its stable
    aliases: []
    usage: /<command> [stable name]
  hstat:
    description: gives you information about your horse
    aliases: []
    usage: /<command>
  race:
    description: horse race controls
    aliases: []
    usage: /<command>
  hspawn:
    description: spawns a horse to the given parameters
    aliases: []
    usage: /[color] [style] [variant] [jump] [speed] [health]

