name: HorseTeleport
version: 1.0
description: >
  Allows horse teleportation
author: Tritania
website: https://github.com/tritania/HorseTeleport

main: org.tritania.horseteleport.HorseTeleport

commands:
  htpa:
    description: Teleport a player on a horse to you
    aliases: []
    usage: /<command> [playername]
  htpahere:
    description: Teleport yourself on a horse to someone else
    aliases: []
    usage: /<command> [playername]
  haccept:
    description: accept a teleport
    aliases: []
    usage: /<command> 
  hdeny:
    description: deny a teleport
    aliases: []
    usage: /<command> 
  setstable:
    description: sets a stable for your horse
    aliases: []
    usage: /<command> 
  stable:
    description: teleports your horse back to its stable
    aliases: []
    usage: /<command> 

